/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SlackLazyImport = createFileRoute('/slack')()
const FlowLazyImport = createFileRoute('/flow')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SlackLazyRoute = SlackLazyImport.update({
  path: '/slack',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/slack.lazy').then((d) => d.Route))

const FlowLazyRoute = FlowLazyImport.update({
  path: '/flow',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/flow.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowLazyImport
      parentRoute: typeof rootRoute
    }
    '/slack': {
      id: '/slack'
      path: '/slack'
      fullPath: '/slack'
      preLoaderRoute: typeof SlackLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/flow': typeof FlowLazyRoute
  '/slack': typeof SlackLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/flow': typeof FlowLazyRoute
  '/slack': typeof SlackLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/flow': typeof FlowLazyRoute
  '/slack': typeof SlackLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flow' | '/slack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flow' | '/slack'
  id: '__root__' | '/' | '/flow' | '/slack'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FlowLazyRoute: typeof FlowLazyRoute
  SlackLazyRoute: typeof SlackLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FlowLazyRoute: FlowLazyRoute,
  SlackLazyRoute: SlackLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flow",
        "/slack"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/flow": {
      "filePath": "flow.lazy.tsx"
    },
    "/slack": {
      "filePath": "slack.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
